name: Coverage Badge
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Test
        run: nix develop --command xc test-cover

      - name: Copy coverage.out to temp
        run: cp coverage.out $RUNNER_TEMP

      - name: Update coverage report
        uses: ncruces/go-coverage-report@57ac6f0f19874f7afbab596105154f08004f482e
        with:
          coverage-file: ${{ runner.temp }}/coverage.out
          report: 'true'
          chart: 'true'
          reuse-go: 'true'
        if: |
          github.event_name == 'push'