name: Coverage Badge
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run Tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage to Wiki
        uses: ncruces/go-coverage-report@v0
        with:
          coverage: coverage.out
          wiki: true

      - name: Upload Coverage Badge
        uses: ncruces/go-coverage-report@v0
        with:
          coverage: coverage.out
          badge: true